gap/gap/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from api.models import MovieResource

movie_resource = MovieResource()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls)),
    path("__debug__/", include("debug_toolbar.urls")),
]

gap/movies/urls.py
from django.urls import include, path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail'),
]

gap/api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'

gap/movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

gap/api/views.py
from django.shortcuts import render

# Create your views here.

gap/gap/views.py
from django.http import HttpResponse
from django.shortcuts import render


# def index(request):
#     topic_value = request.GET.get('topic', '')
#     return HttpResponse(f"<body>welcome to my {topic_value} home page.</body>")

def home(request):
    return render(request, 'home.html')

gap/movies/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

def index(request):
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', { 'movies': movies })

def detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

gap/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
    <dl>
    <dt>Title</dt>
        <dd>{{ movie.title }}</dd>
        <dt>Genre</dt>
        <dd>{{ movie.genre }}</dd>
        <dt>In Stock</dt>
        <dd>{{ movie.number_in_stock }}</dd>
    </dl>
{% endblock %}

gap/movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-bordered table-hover">
        <tr>
            <th>Title</th>
            <th>Genre</th>
            <th>Stock</th>
            <th>Daily Rate</th>
        </tr>
        <tbody>
        {% for movie in movies %}
            <tr>
                <td>
                    <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
                </td>
                <td>{{ movie.genre }}</td>
                <td>{{ movie.number_in_stock }}</td>
                <td>{{ movie.daily_rate }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

gap/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vidly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-light bg-light">
    <span class="navbar-brand mb-0 h1">Vidly</span>
</nav>
<main class="container">
    {% block content %}
    {% endblock %}
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

gap/templates/home.html
{%  extends 'base.html' %}

{%  block content %}
    <a href="{% url 'movies:index' %}">Movies</a>
{%  endblock %}